services:
  db:
    image: postgres:14-alpine
    container_name: xp75-db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/db/migrations:/docker-entrypoint-initdb.d
      - ./config/db/schema.sql:/schema.sql
volumes:
  pgdata:
