services:
  db:
    image: postgres:14-alpine
    container_name: xp75-db
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/db/migrations:/docker-entrypoint-initdb.d
      - ./config/db/schema.sql:/schema.sql
volumes:
  pgdata:
